src/main/java/net/iceja/entities/User.java
/*
Copyright (c) 2019  Ekaterina Alexeevna Ivanova. All rights reserved.
PROPRIETARY. For demo purposes only, not for redistribution or any commercial 
use.
*/

package net.iceja.entities;


import java.util.Objects;



/**
 *
 * @author Ekaterina Alexeevna Ivanova
 */


public class User {
    
    private String fio;
    private String password;
    private String login;
    
    private User(){
        
    }

    public User (String firstname, String lastname, String patronymic){
           this.setFio(firstname);
           this.login = lastname;
           this.password = patronymic;
    }
    
    public User (String fio, String login){
    	this(fio, login, "");
 }


    
    @Override
    public int hashCode(){
        if(password == null || login == null || getFio() == null )
            return 0;
        int code =  (login.charAt(0) * 100000000) + 
                (password.charAt(0)  * 1000000000) +  (getFio().charAt(0) * 100000000) ;
                
        return code;
        
    } 

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.getFio(), other.getFio())) {
            return false;
        }
        if (!Objects.equals(this.login, other.login)) {
            return false;
        }
        if (!Objects.equals(this.password, other.password)) {
            return false;
        }
        return true;
    }
    
    
    @Override
     public String toString(){
         
         return getFio();
     }
   

    /**
     * @return the patronymic
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param patronymic the patronymic to set
     */
    public void setPassword(String patronymic) {
        this.password = patronymic;
    }

    /**
     * @return the lastname
     */
    public String getLogin() {
        return login;
    }

    /**
     * @param lastname the lastname to set
     */
    public void setLogin(String lastname) {
        this.login = lastname;
    }

    public String getFio() {
        return fio;
    }

    public void setFio(String fio) {
        this.fio = fio;
    }


    public enum Gender {
        FEMALE("Ж"),
        MALE("М");
        String name ;
        Gender(String n){
            this.name = n;
        }
    
    }
            
    
}

src/main/java/net/iceja/mailbox/beans/Main.java
/*
Copyright (c) 2019 Ekaterina Alexeevna Ivanova  (iceja.moscow). All rights reserved.
PROPRIETARY. For demo purposes only, not for redistribution or any commercial use.
*/
package net.iceja.mailbox.beans;

import net.iceja.util.Mailer;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import javax.inject.Inject;
import net.iceja.dao.UserManagementDAO;

/*
    @author Ekaterina (iceja.net) Ivanova


 */
@ManagedBean(name = "main",eager = true)
@SessionScoped
public class Main {
    private String message = "";
    private String sender = "";
    @Inject
    UserManagementDAO theUserDao;
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * @return this method called form the webpage, it is for sending me an e-mail
     */
    public String sendmessage(){
        System.out.println("sendmessage " + this.message);
        Mailer.send(sender, message);
        sender = "";
        message="отправлено";
        return "";
    }

    private String locale;

    private static Map<String,Object> countries;
    static {

        countries = new LinkedHashMap<String,Object>();
        countries.put("English", Locale.ENGLISH);
        countries.put("Русский", new Locale("ru", "RU"));
    }

    public Map<String, Object> getCountries() {
        return countries;
    }

    public String getLocale() {
        return locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
        setLanguageLocale(locale);
    }

    //value change event listener
    public void localeChanged(ValueChangeEvent e) {
        String newLocaleValue = e.getNewValue().toString();

        setLanguageLocale(newLocaleValue);
    }

    /**
     * @param - the new local name
     *
     * this method
     */
    private void setLanguageLocale(String newLocaleValue) {
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            if(entry.getValue().toString().equals(newLocaleValue)) {
                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale)entry.getValue());
            }
        }
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }
}

src/main/java/net/iceja/JSFspringbootdemo/HelloBean.java
package net.iceja.JSFspringbootdemo;

import net.iceja.JSFspringbootdemo.MsgService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import javax.faces.view.ViewScoped;
import java.time.LocalDateTime;

@Component
@ViewScoped
public class HelloBean {

    @Autowired
    private MsgService msgService;

    public String getMsg() {
        return msgService.getMsg();
    }
}

src/main/java/net/iceja/homepage/HelloBean.java
package net.iceja.homepage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import javax.faces.view.ViewScoped;
import java.time.LocalDateTime;

@Component
@ViewScoped
public class HelloBean {

    @Autowired
    private MsgService msgService;

    public String getMsg() {
        return msgService.getMsg();
    }
}

src/main/resources/webapp/hello.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
</h:head>

<h:body>
    <h:form>
        <h:outputText id="hello-output" value="#{helloBean.msg}" />
        <br/>

    </h:form>
</h:body>
</html>

src/main/resources/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      lang="en">
<h:head>
    <title>Ekaterina Ivanova (under construction)</title>
    <h:outputStylesheet library="css" name="table-style.css"/>
    <h:outputStylesheet library="css" name="lightbox.css"/>
    <h:outputStylesheet library="css" name="demo.css"/>
    <h:outputStylesheet library="css" name="style.css"/>

    <h:outputScript library="js" name="lightbox.js"/>
    <h:outputScript library="primefaces" name="jquery/jquery.js" target="head"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <meta name="description" content="software development"/>
    <meta name="keywords" content="software development"/>
    <meta name="author" content="Ekaterina Ivanova"/>

</h:head>
<h:body>
    <div class="hero-wrapper">
        <div class="hero">
            <figure>
                <video autoplay="true" muted="true" loop="true" id="myVideo">
                    <source src="dist/background.mp4" type="video/mp4"></source>
                    Your browser does not support HTML5 video.
                </video>
            </figure>
        </div>
    </div>

    <div class="parallax-wraper">
        <div class="navigation">
            <!--                <h1>МЕНЮ И НАВИГАЦИЯ</h1>-->
            <h:form style="text-align: right;">

                <h:commandButton action="#{main.setLocale('ru_RU')}"
                                 value="RUSSIAN" image="dist/images/ru32x32.png" style="color: white;"/>&nbsp;
                <h:commandButton action="#{main.setLocale('en')}"
                                 value="ENGLISH" image="dist/images/us32x32.png" style="color: white;"/>

            </h:form>
        </div>

        <div class="parallax">

            <div class="main1">

                <h:form>
                    <h3><h:outputText value="#{msg['greeting']}"/></h3>
                    <h:outputText value="#{msg['intro.text']}"/>

                </h:form>
                <h:form class="sendform1">

                    <br/><p><span class="p2"><a href="mom/web/index.html">#{msg['moms.art']}</a></span></p><br/>
                    <br/>#{msg['samples']}:<br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/src/">#{msg['allinone']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/com/iceja/">#{msg['3dmod']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/insurance-test">#{msg['insurancetest']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/chatserver_v3/">#{msg['chatserver']}</a></span><br/>
                    <span class="p2"><a
                            href="https://github.com/iva-nova-e-katerina/AllSamples/tree/numbertowords">#{msg['numtowords']}</a></span><br/>
                    <span class="p2"><a
                            href="https://github.com/iva-nova-e-katerina/AllSamples/tree/numbertowords">#{msg['iceja.sources']}</a></span><br/>


                    <br/><span class="p2"><a href="#{msg['resume.link']}">#{msg['resume']}</a></span><br/>
                    <!--a href="dist/images/SCAN0004.JPG" data-lightbox="roadtrip">#{msg['diploma']} 1</a>
                    <a href="dist/images/SCAN0001.JPG" data-lightbox="roadtrip"> 2</a>
                    <a href="dist/images/SCAN0003.JPG" data-lightbox="roadtrip"> 3</a>
                    <a href="dist/images/SCAN0002.JPG" data-lightbox="roadtrip"> 4</a-->
                    <br/>
                    <br/>
                    <br/>
                    #{msg['talk.to.me']}
                    <br/>
                    <!--                        #{msg['sender']}<span><h:inputText value="#{main.sender}"></h:inputText></span><br/>-->
                    <!--                        &lt;!&ndash; #{msg['topic']}<h:inputText value=""><br/&ndash;&gt;-->
                    <!--                        <br/>-->


                    #{msg['sender']}<p:inputText id="email" required="true" label="email" size="13"
                                                 requiredMessage="#{msg['please.enter']}"
                                                 validatorMessage="#{msg['invalid.email']}"
                                                 value="#{main.sender}">

                    <f:validateRegex
                            pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"/>

                </p:inputText>
                    <p:watermark for="email" value="#{msg['email.address']} *"/>
                    <p:message for="email"/>
                    <!--                        <br/>-->
                    <h:inputTextarea value="#{main.message}" cols="80" rows="18" class="almost1001"/>
                    <br/>
                    <h:commandButton value="#{msg['send.button']}" action="#{main.sendmessage()}"></h:commandButton>
                </h:form>
            </div>
        </div>

        <div class="footer">
            <div>
                #{msg['contacts']}:
            </div>
            <div>
                skype: jewelope, telegram: @iceja, jabber: iceja13@xmpp.jp <br/>
                <a href="https://www.facebook.com/soft600">me @ facebook, </a>&nbsp;<a
                    href="https://www.vk.com/sw_development">me @ vk.com, </a>&nbsp;<a
                    href="https://www.twitter.com/iceja13">me @ twitter</a><br/>
                tox: 529918DEB8DA36449538EEDE2AECD056C20DED5EC0CAE1692D52893960903C6BA7C65FD04BF3
            </div>
        </div>
    </div>
<!--    <div class="basement">&bnsp;</div>-->



</h:body>
<script type="application/javascript">
    function ValidateEmail(mail) {
        if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(myForm.emailAddr.value)) {
            return (true)
        }
        alert("You have entered an invalid email address!")
        return (false)
    }
</script>
</html>

src/main/webapp/hello.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
</h:head>

<h:body>
    <h:form>
        <h:outputText id="hello-output" value="#{helloBean.msg}" />
        <br/>

    </h:form>
</h:body>
</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      lang="en">
<h:head>
    <title>Ekaterina Ivanova (under construction)</title>
    <h:outputStylesheet library="css" name="table-style.css"/>
    <h:outputStylesheet library="css" name="lightbox.css"/>
    <h:outputStylesheet library="css" name="demo.css"/>
    <h:outputStylesheet library="css" name="style.css"/>

    <h:outputScript library="js" name="lightbox.js"/>
    <h:outputScript library="primefaces" name="jquery/jquery.js" target="head"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <meta name="description" content="software development"/>
    <meta name="keywords" content="software development"/>
    <meta name="author" content="Ekaterina Ivanova"/>

</h:head>
<h:body>
    <div class="hero-wrapper">
        <div class="hero">
            <figure>
                <video autoplay="true" muted="true" loop="true" id="myVideo">
                    <source src="dist/background.mp4" type="video/mp4"></source>
                    Your browser does not support HTML5 video.
                </video>
            </figure>
        </div>
    </div>

    <div class="parallax-wraper">
        <div class="navigation">
            <!--                <h1>МЕНЮ И НАВИГАЦИЯ</h1>-->
            <h:form style="text-align: right;">

                <h:commandButton action="#{main.setLocale('ru_RU')}"
                                 value="RUSSIAN" image="dist/images/ru32x32.png" style="color: white;"/>&nbsp;
                <h:commandButton action="#{main.setLocale('en')}"
                                 value="ENGLISH" image="dist/images/us32x32.png" style="color: white;"/>

            </h:form>
        </div>

        <div class="parallax">

            <div class="main1">

                <h:form>
                    <h3><h:outputText value="#{msg['greeting']}"/></h3>
                    <h:outputText value="#{msg['intro.text']}"/>

                </h:form>
                <h:form class="sendform1">

                    <br/><p><span class="p2"><a href="mom/web/index.html">#{msg['moms.art']}</a></span></p><br/>
                    <br/>#{msg['samples']}:<br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/src/">#{msg['allinone']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/com/iceja/">#{msg['3dmod']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/insurance-test">#{msg['insurancetest']}</a></span><br/>
                    <span class="p2"><a
                            href="https://bitbucket.org/iva-nova-e-katerina/allinone/src/master/chatserver_v3/">#{msg['chatserver']}</a></span><br/>
                    <span class="p2"><a
                            href="https://github.com/iva-nova-e-katerina/AllSamples/tree/numbertowords">#{msg['numtowords']}</a></span><br/>
                    <span class="p2"><a
                            href="https://github.com/iva-nova-e-katerina/AllSamples/tree/numbertowords">#{msg['iceja.sources']}</a></span><br/>


                    <br/><span class="p2"><a href="#{msg['resume.link']}">#{msg['resume']}</a></span><br/>
                    <!--a href="dist/images/SCAN0004.JPG" data-lightbox="roadtrip">#{msg['diploma']} 1</a>
                    <a href="dist/images/SCAN0001.JPG" data-lightbox="roadtrip"> 2</a>
                    <a href="dist/images/SCAN0003.JPG" data-lightbox="roadtrip"> 3</a>
                    <a href="dist/images/SCAN0002.JPG" data-lightbox="roadtrip"> 4</a-->
                    <br/>
                    <br/>
                    <br/>
                    #{msg['talk.to.me']}
                    <br/>
                    <!--                        #{msg['sender']}<span><h:inputText value="#{main.sender}"></h:inputText></span><br/>-->
                    <!--                        &lt;!&ndash; #{msg['topic']}<h:inputText value=""><br/&ndash;&gt;-->
                    <!--                        <br/>-->


                    #{msg['sender']}<p:inputText id="email" required="true" label="email" size="13"
                                                 requiredMessage="#{msg['please.enter']}"
                                                 validatorMessage="#{msg['invalid.email']}"
                                                 value="#{main.sender}">

                    <f:validateRegex
                            pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"/>

                </p:inputText>
                    <p:watermark for="email" value="#{msg['email.address']} *"/>
                    <p:message for="email"/>
                    <!--                        <br/>-->
                    <h:inputTextarea value="#{main.message}" cols="80" rows="18" class="almost1001"/>
                    <br/>
                    <h:commandButton value="#{msg['send.button']}" action="#{main.sendmessage()}"></h:commandButton>
                </h:form>
            </div>
        </div>

        <div class="footer">
            <div>
                #{msg['contacts']}:
            </div>
            <div>
                skype: jewelope, telegram: @iceja, jabber: iceja13@xmpp.jp <br/>
                <a href="https://www.facebook.com/soft600">me @ facebook, </a>&nbsp;<a
                    href="https://www.vk.com/sw_development">me @ vk.com, </a>&nbsp;<a
                    href="https://www.twitter.com/iceja13">me @ twitter</a><br/>
                tox: 529918DEB8DA36449538EEDE2AECD056C20DED5EC0CAE1692D52893960903C6BA7C65FD04BF3
            </div>
        </div>
    </div>
<!--    <div class="basement">&bnsp;</div>-->



</h:body>
<script type="application/javascript">
    function ValidateEmail(mail) {
        if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(myForm.emailAddr.value)) {
            return (true)
        }
        alert("You have entered an invalid email address!")
        return (false)
    }
</script>
</html>